/**
 * @author Dina & Karoon
 */

package mainPlanner;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class welcomeDialog extends javax.swing.JDialog implements Serializable {
     JTable studyTable, nutritionTable, workoutTable;
     DefaultTableModel studyModel, nutritionModel, workoutModel;
     JPanel weekSummary, logSummary;
     ButtonGroup group;
     JScrollPane scrollPane;
     BufferedImage icon;
     Vector <Object> studyRow, studyColumns, data, nutritionCol, nutritionRow, workoutCol, workoutRow;
    /**
     * Creates new form welcomeDialog
     */
    public welcomeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       try {
        mainFrame.setIconImage(ImageIO.read(new File("C:\\Users\\Karoon\\Documents\\Comp 585\\activitymonitor.jpg")));
    } catch (IOException e) {
        e.printStackTrace();
    }
        
        signInPanel.setVisible(false);
        signUpPanel.setVisible(false);
        mainFrame.setVisible(false);
       
        study.setSelected(true);
        
        data = new Vector<Object>();
        studyColumns = new Vector <Object>();
        studyColumns.add("Date");
        studyColumns.add("Class");
        studyColumns.add("Time Taken");
        studyRow = new Vector <Object>();
        data.add(new Date());
        data.add("");
        data.add("");
        studyRow.add(data);
        studyModel = new DefaultTableModel(studyRow, studyColumns);
        studyTable = new JTable(studyModel);
        studyTable.setShowGrid(true);
        scrollPane = new JScrollPane(studyTable);
        tabbedPane.addTab("Day View", scrollPane);
        studyTable.getParent().setBackground(Color.white);
        
        nutritionCol = new Vector<Object>();
        nutritionCol.add("Date");
        nutritionCol.add("Food/Drink List");
        nutritionCol.add("Calories");
        nutritionCol.add("Time");
        data.add(new Time(16));
        nutritionRow = new Vector<Object>();
        nutritionRow.add(data);
        nutritionModel = new DefaultTableModel(nutritionRow,nutritionCol);
        nutritionTable = new JTable(nutritionModel);
        nutritionTable.setShowGrid(true);
        
        String [] workoutCol = {"Date","Workout Type","Time","Calories Burned"};
        workoutModel = new DefaultTableModel(workoutCol, 3);
        workoutTable = new JTable(workoutModel);
        workoutTable.setShowGrid(true);
        
        weekSummary = new JPanel();
        weekSummary.setBackground(Color.white);
        logSummary = new JPanel();
        logSummary.setBackground(Color.white);
        tabbedPane.addTab("Week View", weekSummary);
        tabbedPane.addTab("Log View", logSummary);
        
        group = new ButtonGroup();
        group.add(study);
        group.add(nutrition);
        group.add(workout);
     
        setupDateColumn(studyTable.getColumnModel().getColumn(0));
    }
    
    //Setup date column
    public void setupDateColumn(TableColumn col) {
   // col.setPreferredWidth(100);
    col.setCellRenderer(new DateRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JFrame();
        leftPanel = new javax.swing.JPanel();
        activities = new java.awt.Label();
        study = new javax.swing.JRadioButton();
        nutrition = new javax.swing.JRadioButton();
        workout = new javax.swing.JRadioButton();
        rightPanel = new javax.swing.JPanel();
        addRow = new javax.swing.JButton();
        deleteRow = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        edit = new javax.swing.JMenu();
        usage = new javax.swing.JMenu();
        author = new javax.swing.JMenu();
        welcomePanel = new javax.swing.JPanel();
        welcomeLbl1 = new javax.swing.JLabel();
        welcomeLbl2 = new javax.swing.JLabel();
        btnNewUser = new javax.swing.JButton();
        btnExistingUser = new javax.swing.JButton();
        signInPanel = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        existUserPassword = new javax.swing.JPasswordField();
        existUsername = new javax.swing.JTextField();
        signInbtn = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        signUpUsername = new javax.swing.JLabel();
        SignUppasswordLbl = new javax.swing.JLabel();
        signUpbtn = new javax.swing.JButton();
        NewUserPassword = new javax.swing.JPasswordField();
        NewUsername = new javax.swing.JTextField();

        mainFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        mainFrame.setTitle("Personal Activity Monitor");
        mainFrame.setMinimumSize(new java.awt.Dimension(752, 530));

        leftPanel.setName(""); // NOI18N

        activities.setAlignment(java.awt.Label.CENTER);
        activities.setBackground(java.awt.SystemColor.activeCaption);
        activities.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        activities.setText("Activities");

        study.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        study.setForeground(new java.awt.Color(255, 0, 51));
        study.setText("Study");

        nutrition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nutrition.setForeground(new java.awt.Color(255, 0, 51));
        nutrition.setText("Nutrition");
        nutrition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutritionActionPerformed(evt);
            }
        });

        workout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        workout.setForeground(new java.awt.Color(255, 0, 51));
        workout.setText("Workout");
        workout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(study)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workout, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nutrition, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(activities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(study)
                .addGap(18, 18, 18)
                .addComponent(nutrition)
                .addGap(18, 18, 18)
                .addComponent(workout)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        mainFrame.getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);

        addRow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRow.setForeground(new java.awt.Color(255, 0, 51));
        addRow.setText("Add Row");

        deleteRow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteRow.setForeground(new java.awt.Color(255, 0, 51));
        deleteRow.setText("Delete Row");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRow)
                .addGap(18, 18, 18)
                .addComponent(deleteRow)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        mainFrame.getContentPane().add(rightPanel, java.awt.BorderLayout.LINE_END);

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mainFrame.getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        file.setText("File");
        menuBar.add(file);

        edit.setText("Edit");
        menuBar.add(edit);

        usage.setText("Usage");
        menuBar.add(usage);

        author.setText("Author");
        menuBar.add(author);

        mainFrame.setJMenuBar(menuBar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome to Student PAM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("welcomeDialog"); // NOI18N

        welcomeLbl1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        welcomeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLbl1.setText("Welcome to PAM");

        welcomeLbl2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        welcomeLbl2.setText("Student Private Activity Monitor");

        btnNewUser.setText("New User");
        btnNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewUser.setName(""); // NOI18N
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        btnExistingUser.setText("Existing User");
        btnExistingUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExistingUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnExistingUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addComponent(welcomeLbl2)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addComponent(welcomeLbl1)
                        .addGap(128, 128, 128))))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(welcomeLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLbl2)
                .addGap(31, 31, 31)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExistingUser)
                    .addComponent(btnNewUser))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        signInPanel.setPreferredSize(new java.awt.Dimension(417, 252));

        usernameLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        usernameLbl.setText("Username:");

        passwordLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        passwordLbl.setText("Password:");

        signInbtn.setText("Sign In");
        signInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(signInPanelLayout.createSequentialGroup()
                        .addComponent(passwordLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(existUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signInPanelLayout.createSequentialGroup()
                        .addComponent(usernameLbl)
                        .addGap(18, 18, 18)
                        .addComponent(existUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addGap(19, 19, 19)
                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(42, 42, 42)
                .addComponent(signInbtn)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        signUpPanel.setPreferredSize(new java.awt.Dimension(417, 252));

        signUpUsername.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        signUpUsername.setText("Username:");

        SignUppasswordLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        SignUppasswordLbl.setText("Password:");

        signUpbtn.setText("Sign Up");
        signUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signUpUsername)
                    .addComponent(SignUppasswordLbl))
                .addGap(18, 18, 18)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NewUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(NewUserPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(signUpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpUsername)
                    .addComponent(NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUppasswordLbl)
                    .addComponent(NewUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(signUpbtn)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signUpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(signUpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExistingUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingUserActionPerformed
        // TODO add your handling code here:
        welcomePanel.setVisible(false);
        signInPanel.setVisible(true);
    }//GEN-LAST:event_btnExistingUserActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        // TODO add your handling code here:
        welcomePanel.setVisible(false);
        signUpPanel.setVisible(true);
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void signInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInbtnActionPerformed
        /* this part is not tested
        User pamUser = new User("Test main", "Test main");
        User retrieveUser = pamUser.deserialize();
        System.out.println("username: " + retrieveUser.getUserName() + " & password: " + retrieveUser.getUserPassword());*/
        setVisible(false);
        mainFrame.setVisible(true);
    }//GEN-LAST:event_signInbtnActionPerformed

    private void signUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpbtnActionPerformed
        User pamUser = new User("Test main", "Test main");
        String username = NewUsername.getText().toString(); //get username textfield data
        String userpassword = NewUserPassword.getPassword().toString(); //get password field data
        
        pamUser.setUserName(username); // set user username
        pamUser.setUserPassword(userpassword); //set user password
        pamUser.initSave(); //save file
        pamUser.printInfo(); //print user information
        
        setVisible(false);
        mainFrame.setVisible(true);
    }//GEN-LAST:event_signUpbtnActionPerformed

    private void nutritionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutritionActionPerformed
        // TODO add your handling code here:
       // evt.getSource();
        scrollPane.setViewportView(nutritionTable);
    }//GEN-LAST:event_nutritionActionPerformed

    private void workoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workoutActionPerformed
        // TODO add your handling code here:
        scrollPane.setViewportView(workoutTable);
    }//GEN-LAST:event_workoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                welcomeDialog dialog = new welcomeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NewUserPassword;
    private javax.swing.JTextField NewUsername;
    private javax.swing.JLabel SignUppasswordLbl;
    private java.awt.Label activities;
    private javax.swing.JButton addRow;
    private javax.swing.JMenu author;
    private javax.swing.JButton btnExistingUser;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton deleteRow;
    private javax.swing.JMenu edit;
    private javax.swing.JPasswordField existUserPassword;
    private javax.swing.JTextField existUsername;
    private javax.swing.JMenu file;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JFrame mainFrame;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButton nutrition;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JButton signInbtn;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signUpUsername;
    private javax.swing.JButton signUpbtn;
    private javax.swing.JRadioButton study;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JMenu usage;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JLabel welcomeLbl1;
    private javax.swing.JLabel welcomeLbl2;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JRadioButton workout;
    // End of variables declaration//GEN-END:variables
}

//Date Renderer
 class DateRender extends DefaultTableCellRenderer {
    @Override
    public Component getTableCellRendererComponent(JTable t,
      Object value, boolean isSelected, boolean hasFocus, 
      int row, int col){
        SimpleDateFormat format = new SimpleDateFormat("EEEE, MMM d, yyyy");
        setValue(format.format((Date) value));
        return this;
    }
 }
